set_property PACKAGE_PIN F7 [get_ports ap_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ap_clk]
create_clock -period 10.000 -name clk100MHz [get_ports ap_clk]

set_property PACKAGE_PIN G6 [get_ports ap_rst]
set_property IOSTANDARD LVCMOS33 [get_ports ap_rst]

set_property PACKAGE_PIN G7 [get_ports ap_start]
set_property IOSTANDARD LVCMOS33 [get_ports ap_start]
set_property PACKAGE_PIN H6 [get_ports ap_done]
set_property IOSTANDARD LVCMOS33 [get_ports ap_done]
set_property PACKAGE_PIN H7 [get_ports ap_idle]
set_property IOSTANDARD LVCMOS33 [get_ports ap_idle]
set_property PACKAGE_PIN J6 [get_ports ap_ready]
set_property IOSTANDARD LVCMOS33 [get_ports ap_ready]

set_property PACKAGE_PIN K6 [get_ports {input_r_address0[9:0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_r_address0[9:0]}]
set_property PACKAGE_PIN M6 [get_ports {input_r_d0[15:0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_r_d0[15:0]}]
set_property PACKAGE_PIN P6 [get_ports {input_r_q0[15:0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_r_q0[15:0]}]
set_property PACKAGE_PIN R6 [get_ports {input_r_ce0}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_r_ce0}]
set_property PACKAGE_PIN T6 [get_ports {input_r_we0}]
set_property IOSTANDARD LVCMOS33 [get_ports {input_r_we0}]

set_property PACKAGE_PIN U6 [get_ports {output_r_address0[9:0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_r_address0[9:0]}]
set_property PACKAGE_PIN W6 [get_ports {output_r_d0[15:0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_r_d0[15:0]}]
set_property PACKAGE_PIN Y6 [get_ports {output_r_q0[15:0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_r_q0[15:0]}]
set_property PACKAGE_PIN AA6 [get_ports {output_r_ce0}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_r_ce0}]
set_property PACKAGE_PIN AB6 [get_ports {output_r_we0}]
set_property IOSTANDARD LVCMOS33 [get_ports {output_r_we0}]
